language: node_js
node_js:
  - 10
install:
  - npm install # npm ci
script:
  - npm run build # npm run docs:build
after_success:
    - ls -a
    - cd public
    - git init
    - git config --global user.name "${U_NAME}"
    - git config --global user.email "${U_EMAIL}"
    - git add -A
    - ls -a
    - git commit -m 'deploy'
    - git push --quiet --force "https://${GITHUB_TOKEN}@github.com/lidongyalin/lidongyalin.github.io.git" master:main