language: node_js
node_js:
  - 10
install:
  - yarn install # npm ci
script:
  - yarn build # npm run docs:build
after_success:
    - cd public
    - git init
    - git config --global user.name "${U_NAME}"
    - git config --global user.email "${U_EMAIL}"
    - git add -A
    - ls
    - git commit -m 'deploy'
    - git push --quiet --force "https://${GITHUB_TOKEN}@github.com/lidongyalin/lidongyalin.github.io.git" master:main